app:
  name: "dpl-test"
  userId: "7c897e89-ae92-4546-8d01-97a76a"
  projectName: "dpl-test"
  namespace: "user-7c897e89-ae92-4546-8d01-97a76a"
  framework: "nextjs"
  containerPort: 3000
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "dpl-test-ns-tochratana-963a758e.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/7c897e89-ae92-4546-8d01-97a76a/dpl-test"
  tag: "7c897e89-ae92-4546-8d01-97a76a-153-cd32aca03f52" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "dpl-test-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
