app:
  name: "reactjs-cactus-template"
  userId: "980e1422-161f-4287-994e-101976"
  projectName: "reactjs-cactus-template"
  namespace: "user-980e1422-161f-4287-994e-101976"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "reactjs-cactus-template-ns-vuthy-tourn-bba33c3e.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/980e1422-161f-4287-994e-101976/reactjs-cactus-template"
  tag: "980e1422-161f-4287-994e-101976-165-0c5161acf551" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-cactus-template-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
