app:
  name: "ansible-nfs-role-itp"
  userId: "0de2b7cd-69fd-432c-9e3d-8d7d70"
  projectName: "ansible-nfs-role-itp"
  namespace: "user-0de2b7cd-69fd-432c-9e3d-8d7d70"
  framework: "static"
  containerPort: 80
  servicePort: 80
  domain: "autonomous-istad.com"
  host: "ansible-nfs-role-itp-ns-sorn-sophamarinet-c2332eff.autonomous-istad.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/0de2b7cd-69fd-432c-9e3d-8d7d70/ansible-nfs-role-itp"
  tag: "0de2b7cd-69fd-432c-9e3d-8d7d70-157-cb60aa1f8b2a" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "ansible-nfs-role-itp-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
