app:
  name: "reactjs-demo-a8s"
  userId: "afd7df8c-f2be-475f-9791-289fd9"
  projectName: "reactjs-demo-a8s"
  namespace: "user-afd7df8c-f2be-475f-9791-289fd9"
  framework: "react"
  containerPort: 80
  servicePort: 80
  domain: "tochratana.com"
  host: "reactjs-demo-a8s-ns-porkeat-c18c6214.tochratana.com" # managed-by-jenkins-host

image:
  repository: "harbor.devith.it.com/deployment-pipeline/afd7df8c-f2be-475f-9791-289fd9/reactjs-demo-a8s"
  tag: "afd7df8c-f2be-475f-9791-289fd9-137-00a04cceda3e" # managed-by-jenkins-image-tag
  pullPolicy: "IfNotPresent"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "reactjs-demo-a8s-tls"

imagePullSecrets:
  - name: "registry-secret"

envJson: |
  []

probes:
  mode: "http"
  startup:
    enabled: false
    path: "/"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    enabled: true
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 3
